### PR TITLE
chore(.github): add release cd

### PR DESCRIPTION
**Pull request by ShaunSHamilton**
- Adds GitHub Action to build + publish image to GHCR
  - Requires `DOCKERHUB_USERNAME` and `DOCKERHUB_PASSWORD` secrets
- Fixes Nodejs, nvm, and PNPM versions in base
- Adds GitHub Action ensuring there is at least one tagged commit on PRs targeting `main`

Why do we even still use the `gitpod/workspace-base` image? Is it just convenience, because we would have to write a lot of our own config otherwise?

**Note:** As mentioned in README change:
> On pushes to `main`, a GitHub Action will build and push the images to Docker Hub. The image tags will be the same as the Git tag associated with the commit.

Therefore, a tag must be provided.

@raisedadead I am not allowed to open a draft PR 😞

### CODE REVIEW

**Comment by raisedadead** [comment]
I was wondering if we could automate creating Git tags too?

**Comment by ShaunSHamilton** [comment]
> I was wondering if we could automate creating Git tags too? 

Definitely, but what mechanism would you suggest to tell the bot whether something is to bump maj/min/pat?

Previously, I have used labels on PRs. But, even that I ditched for a manual release.

**Comment by raisedadead** [comment]
Conventional commits FTW! Their whole point was around SemVer.

**Comment by ShaunSHamilton** [comment]
I did not close this?

I pushed an extra commit - the way I normally do. What has happened here?

**Comment by raisedadead** [comment]
Hmm - IDK, either. Do you want to reach out to GitHub support? Or make a new PR?

**Pull request closed without merging**
